version: '3'
services:
  db:
    image: postgres:12.1
    restart: always
    networks: 
      - "internal"
    env_file:
      - generated/postgres_password
      - generated/selene_postgres_password
      - config.env
    volumes:
    - ./postgres_setup:/docker-entrypoint-initdb.d
    command:
      - -c
      - "listen_addresses=*"
  db_setup:
    image: selene-backend
    build:
      context: ./selene-backend
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
    restart: "on-failure"
    depends_on:
      - db
    networks: 
      - "internal"
    volumes:
    - shared:/shared
    command:
      - bash
      - -c
      - "set -xe && sleep 10 && cd /opt/selene/selene-backend/db/scripts && pipenv run python -u bootstrap_mycroft_db.py && touch /shared/db_bootstrap_done"
      # TODO: Get rid of the sleep above. Open a PR to make the bootstrap script to retry if it fails to connect
      # The postgres image restart itself after running init scripts and this script looses the connection
      # and can't recover.
    env_file: 
      - generated/postgres_password
      - generated/selene_postgres_password
    environment:
      DB_HOST: "db"
  db_wakeword_setup:
    image: postgres:12.1
    restart: "on-failure"
    networks: 
      - "internal"
    depends_on:
      - db
    env_file: 
      - generated/selene_postgres_password
    volumes:
        - "./wakewords:/setup"
        - "shared:/shared"
    entrypoint: "/setup/setup.sh"
  redis:
    image: redis:5.0.7
    networks: 
      - "internal"
    restart: always
  sso:
    image: selene-backend
    build:
      context: ./selene-backend
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
    restart: "on-failure"
    volumes:
    - shared:/shared
    networks: 
      - "internal"
      - "web"
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/sso && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    env_file: 
      - generated/selene_postgres_password
      - generated/jwt_access_secret
      - generated/jwt_refresh_secret
      - generated/jwt_reset_secret
      - generated/encryption_salt
      - config.env
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PORT: 5432
      DB_USER: selene
      GITHUB_CLIENT_ID: <github client id> TODO
      GITHUB_CLIENT_SECRET: <github client secret> TODO
      SELENE_ENVIRONMENT: prod
      SENDGRID_API_KEY: <sendgrid API key> TODO
  account:
    image: selene-backend
    build:
      context: ./selene-backend
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
    restart: "on-failure"
    volumes:
    - shared:/shared
    networks: 
      - "internal"
      - "web"
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/account && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    env_file:
      - generated/selene_postgres_password
      - generated/jwt_access_secret
      - generated/jwt_refresh_secret
      - generated/encryption_salt
      - config.env
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PORT: 5432
      DB_USER: selene
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
  skills_setup:
    image: selene-backend
    build:
      context: ./selene-backend
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
    restart: "on-failure"
    volumes:
    - shared:/shared
    networks: 
      - "internal"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/batch && /usr/local/bin/pipenv install &&  pipenv run python script/load_skill_display_data.py --core-version 19.08 && touch /shared/skills_setup_done
        "
        # TODO: core-version shouldn't be hardcoded (get latest somehow?)
    env_file:
      - generated/selene_postgres_password
      - generated/jwt_access_secret
      - generated/jwt_refresh_secret
      - generated/encryption_salt
      - config_external_accounts.env
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PORT: 5432
      DB_USER: selene
  market:
    image: selene-backend
    build:
      context: ./selene-backend
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
    restart: "on-failure"
    volumes:
    - shared:/shared
    networks: 
      - "internal"
      - "web"
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/skills_setup_done ]; then echo 'Skills downloading and setup not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/market && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    env_file:
      - generated/selene_postgres_password
      - generated/jwt_access_secret
      - generated/jwt_refresh_secret
      - generated/encryption_salt
      - config.env
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PORT: 5432
      DB_USER: selene
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
  devices:
    image: selene-backend
    build:
      context: ./selene-backend
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
    restart: "on-failure"
    volumes:
    - shared:/shared
    networks: 
      - "internal"
      - "web"
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/skills_setup_done ]; then echo 'Skills downloading and setup not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/public && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    env_file:
      - generated/selene_postgres_password
      - generated/jwt_access_secret
      - generated/jwt_refresh_secret
      - generated/encryption_salt
      - config_external_accounts.env
      - config.env
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PORT: 5432
      DB_USER: selene
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SELENE_ENVIRONMENT: prod
  deepspeech:
    image: deepspeech
    build:
      context: ./deepspeech 
    networks: 
      - "web" 
    restart: "on-failure"
    expose:
      - "8080"
  mozilla-tts:
    build:
      context: ./mozilla-tts 
    image: mozilla-tts
    networks: 
      - "web"
    restart: "on-failure"
    expose:
      - "5002"
  selene-ui-market:
    build:
      context: ./selene-ui
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
        application_name: "market"
    image: selene-ui-market
    networks: 
      - "web"
    restart: "on-failure"
  selene-ui-account:
    build:
      context: ./selene-ui
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
        application_name: "account"
    image: selene-ui-account
    networks: 
      - "web"
    restart: "on-failure"
  selene-ui-sso:
    build:
      context: ./selene-ui
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
        application_name: "sso"
    image: selene-ui-sso
    networks: 
      - "web"
    restart: "on-failure"
  # This is and nginx reverse proxy that redirects all subdomains and api
  # endpoints to the correct container.
  selene-ui-proxy:
    build:
      context: selene-ui
      dockerfile: nginxproxy-Dockerfile
      args:
        mycroft_domain: "${MYCROFT_DOMAIN}"
    image: mycroft-nginx-proxy
    restart: "on-failure"
    networks: 
      - "web"
    depends_on:
      - market
      - sso
      - account
      - devices
      - selene-ui-market
      - selene-ui-sso
      - selene-ui-account
    ports:
      - "80:80"
      - "443:443"
networks:
  internal:
  web:
volumes:
  shared:
